
FROM ubuntu
# WORKDIR /app
# COPY . .
# RUN yum -y install man-db
# RUN mandb
# Add a user/file/group to play around with permissions
RUN apt update
RUN apt-get update
RUN apt -y install sudo 

# Make manuals available
RUN apt -y install man-db
RUN apt -y install unminimize
RUN yes | unminimize

# Docker

# Add Docker's official GPG key:
# RUN sudo apt-get -y install ca-certificates curl
# RUN sudo install -m 0755 -d /etc/apt/keyrings
# RUN sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
# RUN sudo chmod a+r /etc/apt/keyrings/docker.asc
  
# Add the repository to Apt sources:
# RUN echo \
#     "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
#     $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
#     sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# RUN sudo apt-get update

# Install Docker packages:
# RUN yes | sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Virtualization
# RUN apt -y install qemu-kvm libvirt-daemon-system virt-manager libvirt-clients virtinst bridge-utils
# wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img
# wget https://cloud-images.ubuntu.com/noble/current/SHA256SUMS.gpg
# wget https://cloud-images.ubuntu.com/noble/current/SHA256SUMS
# sha256sum -c SHA256SUMS 2>&1 | grep OK
# qemu-img info noble-server-cloudimg-arm64.img
# qemu-img resize noble-server-cloudimg-arm64.img 10G

# misc packages
RUN apt -y install debhelper
RUN apt -y install systemd
RUN apt install nano
RUN apt install bash-completion
RUN apt -y install less
RUN apt -y install vim
RUN apt -y install zip
RUN apt -y install git
RUN apt -y install cron
RUN apt -y install anacron
RUN apt -y install at
RUN apt install wget
RUN apt install -y iproute2
RUN apt -y install netplan.io
RUN apt -y install ufw
# Add new installs here

RUN useradd mf
RUN groupadd family
RUN groupadd family2
RUN usermod -aG family mf
RUN usermod -aG family2 mf
RUN touch my_file.txt
RUN chgrp family my_file.txt
RUN chown mf my_file.txt

COPY auto_complete.txt auto_complete.txt
COPY file1 file1
COPY file2 file2
RUN chown mf /auto_complete.txt
RUN cat /auto_complete.txt >> ~/.bashrc
# Copy script to enable UFW
COPY setup-script.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/setup-script.sh
RUN cd /

CMD ["bash", "/usr/local/bin/setup-script.sh"]